name: CD - Build & Push Docker

on:
  push:
    branches: [main]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build de l'image backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/lung-cancer-backend:latest ./backend

      - name: Push de l'image backend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lung-cancer-backend:latest
